---
- hosts: servers
  tasks:
#    - name: Install gcc
#      apt: pkg=build-essential state=present
#      become: yes

    - name: Install pip3
      apt: pkg=python3-pip state=present
      become: yes

#    - name: Install virtualenv
#      shell: python3 pip install virtualenv

